In [1]:
# Dependencies
import pandas as pd
pd.set_option('display.max_columns', 30)

import warnings
warnings.filterwarnings("ignore")

In [5]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

# New Section

In [13]:
# Read in CSV file
fake_jobs_df = pd.read_csv("../content/sample_data/fake_job_postings.csv")
fake_jobs_df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0

In [14]:
# Check for entirely duplicated rows
fake_jobs_df = fake_jobs_df.drop_duplicates()
fake_jobs_df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0

In [15]:
# Check the duplicate descriptions to get an idea
fake_jobs_df.sort_values("description").head(60)

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent
17175,17176,EFL English Language Teachers for Saudi Arabia...,"GB, LND, london",NaN,NaN,NaN,Normal 0 false false fals...,Gender: FemaleStart month: August 2013Must be...,Competitive Basic Salary: 3000 USD ‐ 5000 USD ...,0,0,1,NaN,NaN,NaN,NaN,NaN,0
5166,5167,Final Expense Agent,"US, ,",NaN,NaN,NaN,Normal 0 false false fals...,Life Insurance License,NaN,0,0,1,NaN,NaN,NaN,Insurance,NaN,1
5873,5874,Sales Director,"AE, DU,",Sales,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,NaN,Sales,0
4958,4959,Station Manager - Kefalonia,"GR, F, Lassi",NaN,NaN,AUTOHELLAS S.A. is the largest Rent a Car comp...,Normal 0 false false false ...,Normal 0 false false false ...,We are offering: An attractive remuneration pa...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,"Leisure, Travel & Tourism",Sales,0
13929,13930,Sales Executive,"GB, LDS,",Retail Sales,NaN,HWL Aluminium (part of the HWL windows group) ...,Normal 0 false false false ...,To be considered for the role of Sales Executi...,Generous earning potential,0,0,1,NaN,NaN,NaN,NaN,NaN,0
5765,5766,Pre-Sales Executive,"GR, , Athens",Sales,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Telecommunications,Sales,0
1424,1425,Assistant Marketing Manager,"GR, I, Athens",Marketing,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,1,Full-time,Entry level,Bachelor's Degree,Telecommunications,Marketing,0
14072,14073,Marketing Executive (Native English Speaker),"GR, ,",Marketing,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,0,Full-time,NaN,Bachelor's Degree,Telecommunications,Marketing,0
891,892,Order Entry Ninja Full-time and Part-time,"US, NY, Port Chester",NaN,NaN,NaN,Normal 0 false false false ...,Normal 0 false false false ...,NaN,0,0,0,Full-time,NaN,NaN,Consumer Services,Customer Service,0
1297,1298,Custom Products Account Maestro,"US, NY, Port Chester",NaN,NaN,NaN,Normal 0 false false false ...,Normal 0 false false false ...,NaN,0,0,0,Full-time,Not Applicable,NaN,Consumer Goods,Customer Service,0
882,883,Service Champion Full-time and Part-time,"US, NY, Port Chester",NaN,NaN,NaN,Normal 0 false false false ...,NaN,NaN,0,0,0,Full-time,NaN,NaN,Consumer Goods,Customer Service,0
7736,7737,"Sr Director, Customer Analytics & Business Int...","US, NY, New York",NaN,NaN,"Since 2001, RL Zapin Associates has been a rec...",Normal 0 false false false ...,Normal 0 false false false ...,NaN,0,1,1,Full-time,Director,Bachelor's Degree,Consumer Goods,Data Analyst,0
4978,4979,Client Services Director,"US, CT, Stamford",NaN,NaN,Repucom is the world leader in sports and spon...,Normal 0 false false false ...,» 5+ years experience in account management wi...,» Working with the global market leader in spo...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Sports,NaN,0
5988,5989,Full-Time Job Coach,"US, OR, Portland",NaN,NaN,United Cerebral Palsy of Oregon &amp; SW Washi...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,1,Full-time,Entry level,High School or equivalent,NaN,NaN,0
6123,6124,DevOps/Software Engineer,"GR, , Athens",Engineering,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,0,Full-time,NaN,NaN,Telecommunications,Engineering,0
3870,3871,Junior Connectivity Engineer,"GR, ,",NaN,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,0,Full-time,Entry level,NaN,Telecommunications,Engineering,0
14007,14008,Pre-Sales Executive,NaN,NaN,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Includes an attractive competitive base salary...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Telecommunications,Sales,0
4300,4301,Digital Media Analyst,"AR, ,",NaN,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,0,Full-time,NaN,NaN,Telecommunications,Product Management,0
563,564,Product Manager,"GR, , Athens",Product & Innovation,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,"Knowledge, Skills and Experience 6 years of ex...",We offer a very competitive base salary and be...,0,1,1,Full-time,NaN,NaN,Telecommunications,NaN,0
2664,2665,Engagement Manager (Nigeria),"NG, ,",Engagement,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Telecommunications,Sales,0
492,493,Engagement Manager (South Africa),"ZA, ,",Engagement,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false ...,Normal 0 false false false ...,Salary &amp; BenefitsThe opportunity to learn ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Telecommunications,Sales,0
6490,6491,Administration Assistant,"US, VA, Fairfax",NaN,NaN,FiLo is a leader in custom software applicatio...,Normal 0 false false false ...,NaN,"Medical, Dental &amp; Vision PlanRetirement Sa...",0,1,0,Full-time,Associate,Unspecified,Computer Software,Administrative,0
5243,5244,Administrative Assistant,"US, OH, Celina",NaN,NaN,MRSI is a nonprofit organization established i...,Normal 0 false false false ...,"2-3 years’ experience in a top-level, high-pre...",Normal 0 false false false ...,0,1,1,Full-time,Mid-Senior level,Unspecified,Nonprofit Organization Management,NaN,0
10496,10497,Ejecutivos de Ventas (vendedor de calle),"PA, 8, Panama",AX 20140308/09 (2),NaN,R.H. ÁGIL es una empresa dedicada a ofrecer se...,Normal 0 21 false false fa...,Experiencia comprobable en ventas de calle y d...,Prima por cobranzaCombustibleTeléfono Celular,0,1,1,Full-time,Associate,Some College Coursework Completed,Retail,Sales,0
1983,1984,Mobile Developer,"GR, B, Thessaloniki",R&D,NaN,schooX is a Social Academy where anyone can t...,0 0 1 141 810 O 6 1 950 14.0 ...,The ideal candidate exhibits the following qua...,NaN,0,1,1,Full-time,Associate,NaN,Computer Software,Engineering,0
1879,1880,Children's Services Manager,"US, OR, Portland",NaN,NaN,United Cerebral Palsy of Oregon &amp; SW Washi...,800x600 Normal 0 false false ...,Bachelors’ degree &amp; four years work experi...,The minimum starting salary for this exempt po...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Civic & Social Organization,Management,0
7280,7281,Senior Test Engineer,"NL, , The Hague",NaN,NaN,EUROPEAN DYNAMICS (#URL_c66532ffa1ce76ab447da6...,800x600 Normal 0 false false ...,"Your skills:University degree, with minimum 6 ...",Our offer:If you are seeking a career in an ex...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Information Technology,0
4727,4728,Marketing Associate (full time or part time),"GR, I, ARGYROUPOLIS",NaN,NaN,NaN,Normal 0 false false fa...,Normal 0 false false fa...,NaN,0,0,0,Full-time,Associate,Bachelor's Degree,Information Technology and Services,Information Technology,0
4400,4401,Software Engineer,"GR, I, Marousi - Athens",Software Developmet,17000-32000,Είμαστε ένα Software House το οποίο λειτουργεί...,Normal 0 false false false E...,Normal 0 false false false E...,Normal 0 false false false E...,0,1,1,Full-time,Entry level,Bachelor's Degree,Information Technology and Services,Information Technology,0
615,616,Telesales Advisor,"GB, UKM, Leeds",Sales,NaN,Working at Assurelife we will ensure you have ...,Normal 0 false false false E...,"Experience of sales, ideally telephone basedEx...","Guaranteed first 2 months earnings, uncapped c...",0,1,1,NaN,NaN,NaN,NaN,NaN,0
17379,17380,Marketing Coordinator: Temp to Perm,"US, MA, Cambridge",Marketing,NaN,Pioneering advanced analytics vendor RapidMine...,Normal 0 false false false E...,Responsibilities:· Exercise your creati...,Temporary position is an hourly position with ...,0,1,1,Other,Entry level,Bachelor's Degree,Marketing and Advertising,Marketing,0
1184,1185,Applications Administrator,"GR, I, Athens",Operations,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false E...,Normal 0 false false false E...,Includes attractive competitive base salary an...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Telecommunications,Information Technology,0
901,902,Connectivity Engineer,"GR, I, Athens",Engineering,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false E...,Normal 0 false false false E...,Normal 0 false false false E...,0,1,1,Full-time,NaN,NaN,NaN,Engineering,0
4960,4961,Operational Database Administrator,"GR, I, Athens",Engineering,NaN,Upstream’s mission is to revolutionise the way...,Normal 0 false false false E...,Normal 0 false false false E...,Normal 0 false false false E...,0,1,1,Full-time,Mid-Senior level,NaN,Telecommunications,Engineering,0
6373,6374,Senior Software Developer,"US, CT, Westport",NaN,NaN,•Founded in 2003•10+ years of proven expertise...,Normal 0 false false false E...,Normal 0 false false false E...,Work in an environment that values truth and o...,0,1,1,Contract,Director,Master's Degree,Banking,Information Technology,0
8010,8011,Remote IT Tech,"US, VA, Fairfax",IT,40000-60000,FiLo is a leader in custom software applicatio...,Normal 0 false false false E...,Must have ability to acquire SECRET level secu...,Health Benefits Package OfferedLife Insurance ...,0,1,1,Full-time,Associate,Some College Coursework Completed,Computer Hardware,Information Technology,0
1063,1064,Entrepreneurial CTO for early-stage Start-up,"GR, I, Athens",IT,NaN,Ependys GmbH aspires to build great startups i...,Normal 0 21 false false false ...,Normal 0 21 false false false ...,Generous voting stock and competitive cash rem...,0,1,1,Other,Mid-Senior level,Bachelor's Degree,Internet,Information Technology,0
17556,17557,Customer Service Representative to Enroll Peop...,"US, AR, Little Rock",Customer Service,NaN,Join the Your Phone Connect team and earn mone...,Normal 0 false false false ...,NaN,NaN,0,1,0,Contract,Not Applicable,Unspecified,Telecommunications,Customer Service,1
7691,7692,PR & CORPORATE COMMUNICATIONS ACCOUNT DIRECTOR,"GR, I, Athens",NaN,NaN,MSPS is an award-winning Integrated Marketing ...,Normal 0 false false false ...,Normal 0 false false false ...,NaN,0,1,0,Full-time,Mid-Senior level,NaN,Public Relations and Communications,NaN,0
17737,17738,Customer Service Representative to Enroll Peop...,"US, MD, Baltimore",Customer Service,NaN,Join the Your Phone Connect team and earn mone...,Normal 0 false false false ...,NaN,NaN,0,1,0,NaN,NaN,NaN,NaN,Customer Service,1
17723,17724,Customer Service Representative to Enroll Peop...,"US, MO, Kansas City",Customer Service,NaN,Join the Your Phone Connect team and earn mone...,Normal 0 false false false ...,NaN,NaN,0,1,0,Contract,NaN,NaN,NaN,Customer Service,1
7756,7757,IS TESTER (Rational Functional Tester),"BE, , Brussels",NaN,NaN,EUROPEAN DYNAMICS (#URL_c66532ffa1ce76ab447da6...,Normal 0 false false false ...,Normal 0 false false false ...,Normal 0 false false false ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Information Technology,0
17749,17750,Administrative/Receptionist - $19.25/hr,"US, IN, Indianapolis",Administrative,NaN,NaN,Normal 0 ADMINITRATIVE ASSISTANT This is...,Confident yet easy-going; firm yet flexible; ...,"$19.25/hr plus bonus, great benefits and hours...",0,1,1,NaN,NaN,NaN,NaN,NaN,1
17770,17771,Receptionist - Administrative Assistant,"US, TX, Houston",Administrative Dept,NaN,Titan Business Properties (TBP) is one of coun...,Normal 0 Titan Business Properties (TBP)...,Normal 0 Job Duties:Produce information ...,Normal 0 Benefits: We offer full medical...,0,0,1,Full-time,Entry level,High School or equivalent,Financial Services,Administrative,1
5271,5272,Customer Care Representative,"US, CT, Hartford",Customer Service Dept,NaN,UBG is a private investment firm. We're a fast...,Normal 0 Urban Business Group is now hir...,High school diploma (college preferred)Previou...,14.50/hr (non-negotiable)Medical/dental covera...,0,1,1,NaN,NaN,NaN,NaN,NaN,0
345,346,Kindergarten Teacher,"RU, MOW, Moscow",NaN,36000-40000,"We place highly qualified governors, governess...",A Russian school in the south of Moscow are l...,- All applicants should be currently living in...,- The working hours would be 9-5 Mon-Fri. - Ca...,0,1,0,Full-time,Not Applicable,Unspecified,Primary/Secondary Education,Education,0
14483,14484,Customer Success Manager,"US, ,",Support,45000-45000,NaN,I'm looking for a Customer Success Manager wi...,Experience helping customers Excellent technic...,What you can expect:Work with a fun team and h...,1,0,0,Full-time,Entry level,NaN,Information Technology and Services,Customer Service,0
11503,11504,Sr. Systems Engineering Manager,"US, CA, San Jose",Oil & Energy,NaN,...,SUMMARY: The Sr. Systems Engineering Manage...,"QUALIFICATIONS: Strong technical background, w...",WHAT IS BEING OFFERED:- Very competitive base ...,0,1,1,NaN,NaN,NaN,NaN,NaN,1
14268,14269,"Sr. Marketing Manager, Demand Generation","US, CA, Encino",NaN,NaN,NaN,THE COMPANY: uSamp (#URL_a6a38a7120c0f7ac2d56...,THE RIGHT PERSON: REQUIREMENTS x PERSONAEDUCAT...,WHY USAMP?Be a part of the building the #1 to...,0,0,0,Full-time,Mid-Senior level,Bachelor's Degree,Market Research,Marketing,0
13849,13850,Welcome desk Administrator,"EE, 37, Tallinn",HR,NaN,Want to build a 21st century financial service...,TransferWho?Co-founded by Skype’s first emplo...,"So, what’s the role?Welcome desk administratio...",You will join one of Europe’s most hotly tippe...,0,1,0,NaN,NaN,NaN,NaN,NaN,0
2687,2688,Voluntourist in Kenya,NaN,NaN,NaN,NaN,"Volunteer for IHF in Nakuru, KenyaThe interna...","Requirements:Cost: $150 per week, no applicati...",We are sure that it will be one of the most re...,0,0,0,Part-time,NaN,NaN,NaN,NaN,0
1928,1929,Web Developer,"NZ, N, Auckland",NaN,NaN,Tailor is a digital agency specialising in thr...,"We're looking for a motivated, talented web d...","Technically, you'll have:2+ years experience i...",NaN,0,1,1,Full-time,Associate,Bachelor's Degree,Information Technology and Services,Information Technology,0
17034,17035,Business Analyst with FX (Foreign Exchange),"US, NC, Charlotte",NaN,NaN,e-Solutions Inc. is a talent-driven consulting...,§ Overall Payments Industry Experience &gt; 8...,NaN,NaN,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Information Technology and Services,NaN,0
6379,6380,Managing Consultant - Energy - Upstream - null,"US, TX, Houston",NaN,NaN,RHB Recruitment Ltd is a business process outs...,"""DOMAIN CONSULTANT-L4 : Responsible to provide...",--&gt;Consulting(L3)-Work in capacity of a tru...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0
17571,17572,Work From Home (Easy Money),"US, FL, Orlando,Lake City, Jacksonville,Atlant...",NaN,NaN,DMT Instant Reward. We are Hiring all The Time.,"""Do You Want To Own Your Internet Base Busines...","Computer, Internet and Telephone","Company looking to fill a few CSR places, Job ...",0,1,0,NaN,NaN,NaN,NaN,NaN,1
5441,5442,Easy Money,"US, FL, Deltona",NaN,NaN,DMT Instant Reward. We are Hiring all The Time.,"""Do You Want To Own Your Internet Base Busines...","Computer, Internet and Telephone",Work from home Full-time or Part-time be your ...,0,1,1,NaN,NaN,NaN,NaN,NaN,1
17726,17727,Work From Home,"CA, ON,",NaN,NaN,NaN,"""Let us show you how we've taught others just ...",You Will Be Someone Who Has: Professional mann...,"Earn money in your spare time, part time or fu...",1,0,1,NaN,NaN,NaN,NaN,NaN,1
6074,6075,Experienced Dog Groomer - Costa Mesa,"US, CA, Costa Mesa",Grooming,NaN,NaN,"""Pride is a personal commitment. It is an att...",The Groomer Will. . . -Continue to master the ...,NaN,0,0,1,Full-time,NaN,NaN,NaN,NaN,0
4193,4194,Experienced Dog Groomer - Costa Mesa,US,Grooming,NaN,NaN,"""Pride is a personal commitment. It is an att...",NaN,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0
14118,14119,Experienced Dog Groomer - Costa Mesa,"US, CA, Costa Mesa",Grooming,NaN,NaN,"""Pride is a personal commitment. It is an att...",NaN,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0

In [16]:
# Create column to assess whether or not salary range is provided
fake_jobs_df['salary_provided'] = pd.notna(fake_jobs_df['salary_range'])
fake_jobs_df['benefits_provided'] = pd.notna(fake_jobs_df['benefits'])

fake_jobs_df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,salary_provided,benefits_provided
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,False,False
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,False,True
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,False,False
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,False,True
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0,False,True
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0,False,True
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0,False,False
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0,False,True
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0,False,False

In [17]:
# Check datatypes
fake_jobs_df.dtypes

job_id                  int64
title                  object
location               object
department             object
salary_range           object
company_profile        object
description            object
requirements           object
benefits               object
telecommuting           int64
has_company_logo        int64
has_questions           int64
employment_type        object
required_experience    object
required_education     object
industry               object
function               object
fraudulent              int64
salary_provided          bool
benefits_provided        bool
dtype: object

In [18]:
# Convert Boolean columns to integer
fake_jobs_df[['salary_provided', 'benefits_provided']] = (fake_jobs_df[['salary_provided', 'benefits_provided']]).astype(int)
fake_jobs_df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,salary_provided,benefits_provided
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,0,0
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,0,1
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,0,0
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,0,1
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0,0,1
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0,0,1
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0,0,0
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0,0,1
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0,0,0

In [19]:
# Separate Location into Country, State, City
fake_jobs_df['country'], fake_jobs_df['state/province'], fake_jobs_df['city'] = fake_jobs_df['location'].str.split(',', 2).str
fake_jobs_df

,job_id,title,location,department,salary_range,company_profile,description,requirements,benefits,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,industry,function,fraudulent,salary_provided,benefits_provided,country,state/province,city
0,1,Marketing Intern,"US, NY, New York",Marketing,NaN,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,1,0,Other,Internship,NaN,NaN,Marketing,0,0,0,US,NY,New York
1,2,Customer Service - Cloud Video Production,"NZ, , Auckland",Success,NaN,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,0,1,0,Full-time,Not Applicable,NaN,Marketing and Advertising,Customer Service,0,0,1,NZ,,Auckland
2,3,Commissioning Machinery Assistant (CMA),"US, IA, Wever",NaN,NaN,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,1,0,NaN,NaN,NaN,NaN,NaN,0,0,0,US,IA,Wever
3,4,Account Executive - Washington DC,"US, DC, Washington",Sales,NaN,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,Computer Software,Sales,0,0,1,US,DC,Washington
4,5,Bill Review Manager,"US, FL, Fort Worth",NaN,NaN,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Hospital & Health Care,Health Care Provider,0,0,1,US,FL,Fort Worth
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Account Director - Distribution,"CA, ON, Toronto",Sales,NaN,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Sales,0,0,1,CA,ON,Toronto
17876,17877,Payroll Accountant,"US, PA, Philadelphia",Accounting,NaN,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,Internet,Accounting/Auditing,0,0,1,US,PA,Philadelphia
17877,17878,Project Cost Control Staff Engineer - Cost Con...,"US, TX, Houston",NaN,NaN,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,Full-time,NaN,NaN,NaN,NaN,0,0,0,US,TX,Houston
17878,17879,Graphic Designer,"NG, LA, Lagos",NaN,NaN,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,0,0,1,Contract,Not Applicable,Professional,Graphic Design,Design,0,0,1,NG,LA,Lagos
17879,17880,Web Application Developers,"NZ, N, Wellington",Engineering,NaN,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,1,1,Full-time,Mid-Senior level,NaN,Computer Software,Engineering,0,0,0,NZ,N,Wellington

In [20]:
# Reorganize Columns
fake_jobs_df = fake_jobs_df[['job_id', 'city', 'state/province', 'country', 'title', 'department', 'industry', 
                             'function', 'salary_range', 'salary_provided', 'company_profile', 'description', 
                             'requirements', 'benefits', 'benefits_provided', 'telecommuting', 'has_company_logo', 
                             'has_questions', 'employment_type', 'required_experience', 'required_education', 
                             'fraudulent']]
fake_jobs_df

,job_id,city,state/province,country,title,department,industry,function,salary_range,salary_provided,company_profile,description,requirements,benefits,benefits_provided,telecommuting,has_company_logo,has_questions,employment_type,required_experience,required_education,fraudulent
0,1,New York,NY,US,Marketing Intern,Marketing,NaN,Marketing,NaN,0,"We're Food52, and we've created a groundbreaki...","Food52, a fast-growing, James Beard Award-winn...",Experience with content management systems a m...,NaN,0,0,1,0,Other,Internship,NaN,0
1,2,Auckland,,NZ,Customer Service - Cloud Video Production,Success,Marketing and Advertising,Customer Service,NaN,0,"90 Seconds, the worlds Cloud Video Production ...",Organised - Focused - Vibrant - Awesome!Do you...,What we expect from you:Your key responsibilit...,What you will get from usThrough being part of...,1,0,1,0,Full-time,Not Applicable,NaN,0
2,3,Wever,IA,US,Commissioning Machinery Assistant (CMA),NaN,NaN,NaN,NaN,0,Valor Services provides Workforce Solutions th...,"Our client, located in Houston, is actively se...",Implement pre-commissioning and commissioning ...,NaN,0,0,1,0,NaN,NaN,NaN,0
3,4,Washington,DC,US,Account Executive - Washington DC,Sales,Computer Software,Sales,NaN,0,Our passion for improving quality of life thro...,THE COMPANY: ESRI – Environmental Systems Rese...,"EDUCATION: Bachelor’s or Master’s in GIS, busi...",Our culture is anything but corporate—we have ...,1,0,1,0,Full-time,Mid-Senior level,Bachelor's Degree,0
4,5,Fort Worth,FL,US,Bill Review Manager,NaN,Hospital & Health Care,Health Care Provider,NaN,0,SpotSource Solutions LLC is a Global Human Cap...,JOB TITLE: Itemization Review ManagerLOCATION:...,QUALIFICATIONS:RN license in the State of Texa...,Full Benefits Offered,1,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17875,17876,Toronto,ON,CA,Account Director - Distribution,Sales,Computer Software,Sales,NaN,0,Vend is looking for some awesome new talent to...,Just in case this is the first time you’ve vis...,To ace this role you:Will eat comprehensive St...,What can you expect from us?We have an open cu...,1,0,1,1,Full-time,Mid-Senior level,NaN,0
17876,17877,Philadelphia,PA,US,Payroll Accountant,Accounting,Internet,Accounting/Auditing,NaN,0,WebLinc is the e-commerce platform and service...,The Payroll Accountant will focus primarily on...,- B.A. or B.S. in Accounting- Desire to have f...,Health &amp; WellnessMedical planPrescription ...,1,0,1,1,Full-time,Mid-Senior level,Bachelor's Degree,0
17877,17878,Houston,TX,US,Project Cost Control Staff Engineer - Cost Con...,NaN,NaN,NaN,NaN,0,We Provide Full Time Permanent Positions for m...,Experienced Project Cost Control Staff Enginee...,At least 12 years professional experience.Abil...,NaN,0,0,0,0,Full-time,NaN,NaN,0
17878,17879,Lagos,LA,NG,Graphic Designer,NaN,Graphic Design,Design,NaN,0,NaN,Nemsia Studios is looking for an experienced v...,1. Must be fluent in the latest versions of Co...,Competitive salary (compensation will be based...,1,0,0,1,Contract,Not Applicable,Professional,0
17879,17880,Wellington,N,NZ,Web Application Developers,Engineering,Computer Software,Engineering,NaN,0,Vend is looking for some awesome new talent to...,Who are we?Vend is an award winning web based ...,We want to hear from you if:You have an in-dep...,NaN,0,0,1,1,Full-time,Mid-Senior level,NaN,0

In [21]:
# Save Cleaned/Organized df to csv
fake_jobs_df.to_csv("fake_jobs_clean.csv", index=False)